### ISSUE TITLE
Delete Duplicate Directory

### ISSUE THREAD

**Issue by sshdopey** [ALX-SE-Algorithmia/Demo-Project#24] opened 2023-07-11 15:39 UTC
Hello @MartyOfMCA, you merged the PR #22  from @Namujibril, and it contained a duplicate directory, where one starts with a Capital letter N (`Namujibril`)and the other is all lower case (`namujibril`) as the naming convention goes, Please do well to fix this by deleting the directory [Namujibril](https://github.com/ALX-SE-Algorithmia/Demo-Project/tree/main/Namujibril). @Namujibril can fix this or someone else willing to can.

If you want to give a try to fixing this issue please respond `assign to me` and it will be assigned to you. Do not begin working to fix this issue if it isn't assigned to you

**Comment by Youngman-d-coder** [comment] 2023-07-11 16:18
Assign to me

**Comment by DestinedCodes** [comment] 2023-07-11 16:51
@Jarhodee the issue is currently assigned to @Youngman-d-coder . Keep and eye for future Issues and also do well to send in your version of the Demo Project

**Comment by Jarhodee** [comment] 2023-07-11 16:55
sure. thank you

**Comment by Youngman-d-coder** [comment] 2023-07-11 17:13
fixed!
I fixed the issue of duplicate directory, removing the (Namujibril) while leaving the file (namujibril) since it goes according to allowed naming convention of the project!

**Comment by DestinedCodes** [comment] 2023-07-11 17:16
Thanks for the Hot Fix if this issue in PR #25. We're going somewhere. Issue will be closed since this is fixed

**Closed as completed** 2023-07-11 17:17 UTC
Labels: bug, good first issue, help wanted
